### ISSUE TITLE
Buildroot setup - to build for multiple boards

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/machinery#30]
The main issue we're currently having is to prepare a new release of Kerberos.io. How it's working for the moment:

* Flash a base OS to the SD-card.
* Install the machinery and web repositories, with their dependencies (Nginx, etc).
* Backup the SD-card and export to .img
* Upload .img to public website.

Each of the steps above needs to be repeated for every device (processor). It takes a lot of time to do so, and it's a very operational task. It would be great to have an automated build flow, suggested by @JasonSwindle (#13). Combining Buildroot with a docker image of kerberos will be more efficient for development and release management.

**Comment by ccrisan** [comment]
I have prepared a stripped-down version of motionEyeOS (basically just the OS w/o motion or motionEye). It's not a fork *per se* and I don't think it should be. It's currently on my computer waiting to be pushed somewhere.

I took the liberty to name the OS "kios" as I needed a name. Please feel free to suggest any other name.

I believe a repo should be created for it and we should start "moving" Kerberios.io-specific packages to the distro's build system, so that everything gets built automatically with one command (I'd be happy to help adding these custom packages to the BuildRoot system).

**Comment by cedricve** [comment]
Great job ccrissan! I've created a repo called "kios", which contains 2 branches "master" and "develop".
We can push a first version to the develop [branch](https://github.com/kerberos-io/kios/tree/develop).
